version: "3.1"
services:
  db:
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "todos"
    volumes:
      - /tmp/mongo-data:/data/db mongo
